# Generated by Django 3.2.25 on 2026-04-08 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_auto_20260408_0816"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="ingredient",
            new_name="ingredients",
        ),
    ]
